package com.study.myspringstudydiary.service;

import com.study.myspringstudydiary.common.Page;
import com.study.myspringstudydiary.dto.request.StudyLogCreateRequest;
import com.study.myspringstudydiary.dto.request.StudyLogUpdateRequest;
import com.study.myspringstudydiary.dto.response.StudyLogResponse;
import com.study.myspringstudydiary.dto.response.StudyLogDeleteResponse;
import com.study.myspringstudydiary.exception.ResourceNotFoundException;
import com.study.myspringstudydiary.entity.Category;
import com.study.myspringstudydiary.entity.StudyLog;
import com.study.myspringstudydiary.entity.Understanding;
import com.study.myspringstudydiary.dao.StudyLogDao;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;

import java.time.LocalDate;
import java.util.List;
import java.util.Optional;
import java.util.stream.Collectors;

/**
 * Study Log Service with Lombok
 *
 * @Slf4j - Automatically creates a logger instance
 * @RequiredArgsConstructor - Generates constructor for final fields
 */
@Slf4j
@Service
@RequiredArgsConstructor  // Automatically generates constructor injection
public class StudyLogService {

    private final StudyLogDao studyLogDao;
    // Constructor is automatically generated by @RequiredArgsConstructor

    // 최대 페이지 크기 상수
    private static final int MAX_PAGE_SIZE = 100;

    // ========== CREATE ==========

    /**
     * 학습 일지 생성
     * @param request 생성 요청 DTO
     * @return 생성된 학습 일지 응답 DTO
     */
    public StudyLogResponse createStudyLog(StudyLogCreateRequest request) {
        log.info("Creating study log with title: {}", request.getTitle());

        // 1. 요청 데이터 유효성 검증
        validateCreateRequest(request);

        // 2. DTO → Entity 변환 (Using Builder pattern with Lombok)
        StudyLog studyLog = request.toEntity();

        // 3. 저장 (DAO 사용)
        StudyLog savedStudyLog = studyLogDao.save(studyLog);
        log.info("Successfully created study log with ID: {}", savedStudyLog.getId());

        // 4. Entity → Response DTO 변환 후 반환
        return StudyLogResponse.from(savedStudyLog);
    }

    // ========== READ ==========

    /**
     * 모든 학습 일지 조회
     * @return 모든 학습 일지 응답 DTO 리스트
     */
    public List<StudyLogResponse> getAllStudyLogs() {
        // 1. DAO에서 모든 학습 일지 조회
        List<StudyLog> studyLogs = studyLogDao.findAll();

        // 2. Entity 리스트 → Response DTO 리스트 변환
        return studyLogs.stream()
                .map(StudyLogResponse::from)
                .collect(Collectors.toList());
    }

    /**
     * ID로 학습 일지 조회
     * @param id 조회할 학습 일지 ID
     * @return 학습 일지 응답 DTO
     */
    public StudyLogResponse getStudyLogById(Long id) {
        log.debug("Fetching study log with ID: {}", id);

        // 1. DAO에서 ID로 조회 (Optional 반환)
        Optional<StudyLog> studyLogOpt = studyLogDao.findById(id);

        // 2. 존재하지 않으면 예외 처리
        StudyLog studyLog = studyLogOpt.orElseThrow(() -> {
            log.warn("Study log not found with ID: {}", id);
            return new ResourceNotFoundException("Study Log", id);
        });

        // 3. Entity → Response DTO 변환 후 반환
        return StudyLogResponse.from(studyLog);
    }

    /**
     * 날짜로 학습 일지 조회
     * @param date 조회할 날짜
     * @return 해당 날짜의 학습 일지 리스트
     */
    public List<StudyLogResponse> getStudyLogsByDate(LocalDate date) {
        List<StudyLog> studyLogs = studyLogDao.findByStudyDate(date);
        return studyLogs.stream()
                .map(StudyLogResponse::from)
                .collect(Collectors.toList());
    }

    /**
     * 카테고리로 학습 일지 조회
     * @param category 조회할 카테고리
     * @return 해당 카테고리의 학습 일지 리스트
     */
    public List<StudyLogResponse> getStudyLogsByCategory(Category category) {
        List<StudyLog> studyLogs = studyLogDao.findByCategory(category.toString());
        return studyLogs.stream()
                .map(StudyLogResponse::from)
                .collect(Collectors.toList());
    }

    /**
     * 카테고리로 학습 일지 조회 (String 버전)
     * @param categoryStr 조회할 카테고리 문자열
     * @return 해당 카테고리의 학습 일지 리스트
     */
    public List<StudyLogResponse> getStudyLogsByCategoryString(String categoryStr) {
        // 유효한 카테고리인지 확인
        Category category;
        try {
            category = Category.valueOf(categoryStr.toUpperCase());
        } catch (IllegalArgumentException e) {
            throw new IllegalArgumentException("유효하지 않은 카테고리입니다: " + categoryStr);
        }
        return getStudyLogsByCategory(category);
    }

    // ========== PAGING ==========

    /**
     * 전체 학습 일지 페이징 조회
     * @param page 페이지 번호 (0-based)
     * @param size 페이지 크기
     * @return 페이징된 학습 일지 응답
     */
    public Page<StudyLogResponse> getStudyLogsWithPaging(int page, int size) {
        // 파라미터 유효성 검증
        page = Math.max(0, page);  // 음수 방지
        size = Math.min(Math.max(1, size), MAX_PAGE_SIZE);  // 1~100 범위

        Page<StudyLog> studyLogPage = studyLogDao.findAllWithPaging(page, size);

        // Entity -> DTO 변환
        List<StudyLogResponse> content = studyLogPage.getContent().stream()
                .map(StudyLogResponse::from)
                .collect(Collectors.toList());

        return new Page<>(content, page, size, studyLogPage.getTotalElements());
    }

    /**
     * 카테고리별 학습 일지 페이징 조회
     * @param categoryStr 카테고리 문자열
     * @param page 페이지 번호
     * @param size 페이지 크기
     * @return 페이징된 학습 일지 응답
     */
    public Page<StudyLogResponse> getStudyLogsByCategoryWithPaging(String categoryStr, int page, int size) {
        page = Math.max(0, page);
        size = Math.min(Math.max(1, size), MAX_PAGE_SIZE);

        // 카테고리 유효성 검증
        if (categoryStr == null || categoryStr.isBlank()) {
            return new Page<>(List.of(), page, size, 0);
        }

        Page<StudyLog> studyLogPage = studyLogDao.findByCategoryWithPaging(categoryStr.toUpperCase(), page, size);

        List<StudyLogResponse> content = studyLogPage.getContent().stream()
                .map(StudyLogResponse::from)
                .collect(Collectors.toList());

        return new Page<>(content, page, size, studyLogPage.getTotalElements());
    }

    /**
     * 검색 + 페이징 조회
     * @param titleKeyword 제목 키워드
     * @param categoryStr 카테고리 문자열
     * @param startDate 시작 날짜
     * @param endDate 종료 날짜
     * @param page 페이지 번호
     * @param size 페이지 크기
     * @return 페이징된 학습 일지 응답
     */
    public Page<StudyLogResponse> searchStudyLogsWithPaging(
            String titleKeyword,
            String categoryStr,
            LocalDate startDate,
            LocalDate endDate,
            int page,
            int size) {

        page = Math.max(0, page);
        size = Math.min(Math.max(1, size), MAX_PAGE_SIZE);

        // 카테고리 문자열을 대문자로 변환 (유효성 검증은 DAO에서 처리)
        String category = null;
        if (categoryStr != null && !categoryStr.isBlank()) {
            category = categoryStr.toUpperCase();
        }

        Page<StudyLog> studyLogPage = studyLogDao.searchWithPaging(
                titleKeyword, category, startDate, endDate, page, size);

        List<StudyLogResponse> content = studyLogPage.getContent().stream()
                .map(StudyLogResponse::from)
                .collect(Collectors.toList());

        return new Page<>(content, page, size, studyLogPage.getTotalElements());
    }

    /**
     * 카테고리별 학습 일지 개수 조회
     * @param categoryStr 카테고리 문자열
     * @return 해당 카테고리의 학습 일지 개수
     */
    public long getStudyLogCountByCategory(String categoryStr) {
        if (categoryStr == null || categoryStr.isBlank()) {
            return 0;
        }
        return studyLogDao.countByCategory(categoryStr.toUpperCase());
    }

    // ========== UPDATE ==========

    /**
     * 학습 일지 수정
     *
     * @param id 수정할 학습 일지 ID
     * @param request 수정 요청 데이터
     * @return 수정된 학습 일지 응답
     */
    public StudyLogResponse updateStudyLog(Long id, StudyLogUpdateRequest request) {

        // 1. 기존 학습 일지 조회 (DAO 사용)
        Optional<StudyLog> studyLogOpt = studyLogDao.findById(id);
        StudyLog studyLog = studyLogOpt.orElseThrow(() ->
            new ResourceNotFoundException("Study Log", id)
        );

        // 2. 수정할 내용이 있는지 확인
        if (request.hasNoUpdates()) {
            throw new IllegalArgumentException("수정할 내용이 없습니다.");
        }

        // 3. 수정할 값들의 유효성 검증
        validateUpdateRequest(request);

        // 4. 카테고리와 이해도 변환 (null이 아닌 경우에만)
        Category category = null;
        if (request.getCategory() != null) {
            try {
                category = Category.valueOf(request.getCategory().toUpperCase());
            } catch (IllegalArgumentException e) {
                throw new IllegalArgumentException(
                    "유효하지 않은 카테고리입니다: " + request.getCategory());
            }
        }

        Understanding understanding = null;
        if (request.getUnderstanding() != null) {
            try {
                understanding = Understanding.valueOf(request.getUnderstanding().toUpperCase());
            } catch (IllegalArgumentException e) {
                throw new IllegalArgumentException(
                    "유효하지 않은 이해도입니다: " + request.getUnderstanding());
            }
        }

        // 5. Entity 업데이트 (null이 아닌 값만 반영)
        studyLog.update(
            request.getTitle(),
            request.getContent(),
            category,
            understanding,
            request.getStudyTime(),
            request.getStudyDate()
        );

        // 6. 저장 및 응답 반환 (DAO 사용)
        StudyLog updatedStudyLog = studyLogDao.update(studyLog);
        return StudyLogResponse.from(updatedStudyLog);
    }

    // ========== DELETE ==========

    /**
     * 학습 일지를 삭제합니다.
     *
     * @param id 삭제할 학습 일지 ID
     * @return 삭제 결과 응답
     * @throws ResourceNotFoundException 해당 ID의 학습 일지가 없는 경우
     */
    public StudyLogDeleteResponse deleteStudyLog(Long id) {
        // 1. 존재 여부 확인 (DAO 사용)
        if (!studyLogDao.existsById(id)) {
            throw new ResourceNotFoundException("Study Log", id);
        }

        // 2. 삭제 수행 (DAO 사용)
        studyLogDao.deleteById(id);

        // 3. 삭제 결과 반환
        return StudyLogDeleteResponse.of(id);
    }

    /**
     * 학습 일지 총 개수를 반환합니다.
     *
     * @return 학습 일지 총 개수
     */
    public long getStudyLogCount() {
        return studyLogDao.count();
    }

    // ========== PRIVATE METHODS ==========

    /**
     * 생성 요청 유효성 검증
     */
    private void validateCreateRequest(StudyLogCreateRequest request) {
        if (request.getTitle() == null || request.getTitle().trim().isEmpty()) {
            throw new IllegalArgumentException("학습 주제는 필수입니다.");
        }
        if (request.getTitle().length() > 100) {
            throw new IllegalArgumentException("학습 주제는 100자를 초과할 수 없습니다.");
        }
        if (request.getContent() == null || request.getContent().trim().isEmpty()) {
            throw new IllegalArgumentException("학습 내용은 필수입니다.");
        }
        if (request.getContent().length() > 1000) {
            throw new IllegalArgumentException("학습 내용은 1000자를 초과할 수 없습니다.");
        }
        if (request.getStudyTime() == null || request.getStudyTime() < 1) {
            throw new IllegalArgumentException("학습 시간은 1분 이상이어야 합니다.");
        }
    }

    /**
     * 수정 요청 유효성 검증
     * null이 아닌 값만 검증합니다.
     */
    private void validateUpdateRequest(StudyLogUpdateRequest request) {
        if (request.getTitle() != null) {
            if (request.getTitle().trim().isEmpty()) {
                throw new IllegalArgumentException("학습 주제는 빈 값일 수 없습니다.");
            }
            if (request.getTitle().length() > 100) {
                throw new IllegalArgumentException("학습 주제는 100자를 초과할 수 없습니다.");
            }
        }

        if (request.getContent() != null) {
            if (request.getContent().trim().isEmpty()) {
                throw new IllegalArgumentException("학습 내용은 빈 값일 수 없습니다.");
            }
            if (request.getContent().length() > 1000) {
                throw new IllegalArgumentException("학습 내용은 1000자를 초과할 수 없습니다.");
            }
        }

        if (request.getStudyTime() != null && request.getStudyTime() < 1) {
            throw new IllegalArgumentException("학습 시간은 1분 이상이어야 합니다.");
        }

        if (request.getStudyDate() != null && request.getStudyDate().isAfter(LocalDate.now())) {
            throw new IllegalArgumentException("학습 날짜는 미래일 수 없습니다.");
        }
    }
}