package com.study.myspringstudydiary.service;

import com.study.myspringstudydiary.dto.request.StudyLogCreateRequest;
import com.study.myspringstudydiary.dto.request.StudyLogUpdateRequest;
import com.study.myspringstudydiary.dto.response.StudyLogResponse;
import com.study.myspringstudydiary.dto.response.StudyLogDeleteResponse;
import com.study.myspringstudydiary.exception.ForbiddenException;
import com.study.myspringstudydiary.exception.ResourceNotFoundException;
import com.study.myspringstudydiary.entity.Category;
import com.study.myspringstudydiary.entity.StudyLog;
import com.study.myspringstudydiary.entity.Understanding;
import com.study.myspringstudydiary.dao.StudyLogDao;
import com.study.myspringstudydiary.security.CustomUserDetails;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.stereotype.Service;

import java.util.List;
import java.util.Optional;
import java.util.stream.Collectors;

/**
 * Study Log Service with Lombok
 *
 * @Slf4j - Automatically creates a logger instance
 * @RequiredArgsConstructor - Generates constructor for final fields
 */
@Slf4j
@Service
@RequiredArgsConstructor  // Automatically generates constructor injection
public class StudyLogService {

    private final StudyLogDao studyLogDao;
    // Constructor is automatically generated by @RequiredArgsConstructor

    /**
     * Get current authenticated user ID from SecurityContext
     * @return Current user ID
     * @throws IllegalStateException if user is not authenticated
     */
    private Long getCurrentUserId() {
        Authentication authentication = SecurityContextHolder.getContext().getAuthentication();

        if (authentication == null || !authentication.isAuthenticated()) {
            throw new IllegalStateException("User is not authenticated");
        }

        Object principal = authentication.getPrincipal();
        if (principal instanceof CustomUserDetails) {
            return ((CustomUserDetails) principal).getUserId();
        }

        throw new IllegalStateException("Invalid authentication principal type");
    }

    /**
     * 학습 일지 생성
     * @param request 생성 요청 DTO
     * @return 생성된 학습 일지 응답 DTO
     */
    public StudyLogResponse createStudyLog(StudyLogCreateRequest request) {
        log.info("Creating study log with title: {}", request.getTitle());

        // 1. Get current authenticated user ID
        Long userId = getCurrentUserId();

        // 2. DTO → Entity 변환 (Using Builder pattern with Lombok)
        // Validation is now handled by @Valid annotation in Controller
        StudyLog studyLog = request.toEntity(userId);

        // 3. 저장 (DAO 사용)
        StudyLog savedStudyLog = studyLogDao.save(studyLog);
        log.info("Successfully created study log with ID: {} for user: {}", savedStudyLog.getId(), userId);

        // 4. Entity → Response DTO 변환 후 반환
        return StudyLogResponse.from(savedStudyLog);
    }

    /**
     * 모든 학습 일지 조회 (현재 사용자 것만)
     * @return 현재 사용자의 모든 학습 일지 응답 DTO 리스트
     */
    public List<StudyLogResponse> getAllStudyLogs() {
        // 1. Get current authenticated user ID
        Long userId = getCurrentUserId();

        // 2. DAO에서 현재 사용자의 모든 학습 일지 조회
        List<StudyLog> studyLogs = studyLogDao.findByUserId(userId);

        // 3. Entity 리스트 → Response DTO 리스트 변환
        return studyLogs.stream()
                .map(StudyLogResponse::from)
                .collect(Collectors.toList());
    }

    /**
     * ID로 학습 일지 조회
     * @param id 조회할 학습 일지 ID
     * @return 학습 일지 응답 DTO
     */
    public StudyLogResponse getStudyLogById(Long id) {
        log.debug("Fetching study log with ID: {}", id);

        // 1. Get current authenticated user ID
        Long userId = getCurrentUserId();

        // 2. DAO에서 ID로 조회 (Optional 반환)
        Optional<StudyLog> studyLogOpt = studyLogDao.findById(id);

        // 3. 존재하지 않으면 예외 처리
        StudyLog studyLog = studyLogOpt.orElseThrow(() -> {
            log.warn("Study log not found with ID: {}", id);
            return new ResourceNotFoundException("Study Log", id);
        });

        // 4. Verify ownership
        if (!studyLog.getUserId().equals(userId)) {
            log.warn("User {} attempted to access study log {} owned by user {}", userId, id, studyLog.getUserId());
            throw new ForbiddenException("Study Log", id);
        }

        // 5. Entity → Response DTO 변환 후 반환
        return StudyLogResponse.from(studyLog);
    }

    /**
     * 학습 일지 수정
     *
     * @param id 수정할 학습 일지 ID
     * @param request 수정 요청 데이터
     * @return 수정된 학습 일지 응답
     */
    public StudyLogResponse updateStudyLog(Long id, StudyLogUpdateRequest request) {

        // 1. Get current authenticated user ID
        Long userId = getCurrentUserId();

        // 2. 기존 학습 일지 조회 (DAO 사용)
        Optional<StudyLog> studyLogOpt = studyLogDao.findById(id);
        StudyLog studyLog = studyLogOpt.orElseThrow(() ->
            new ResourceNotFoundException("Study Log", id)
        );

        // 3. Verify ownership
        if (!studyLog.getUserId().equals(userId)) {
            log.warn("User {} attempted to update study log {} owned by user {}", userId, id, studyLog.getUserId());
            throw new ForbiddenException("Study Log", id);
        }

        // 4. 수정할 내용이 있는지 확인 (Business logic validation)
        if (request.hasNoUpdates()) {
            throw new IllegalArgumentException("수정할 내용이 없습니다.");
        }

        // 5. 카테고리와 이해도 변환 (null이 아닌 경우에만)
        // Validation is now handled by @Valid annotation in Controller
        Category category = null;
        if (request.getCategory() != null) {
            category = Category.valueOf(request.getCategory().toUpperCase());
        }

        Understanding understanding = null;
        if (request.getUnderstanding() != null) {
            understanding = Understanding.valueOf(request.getUnderstanding().toUpperCase());
        }

        // 6. Entity 업데이트 (null이 아닌 값만 반영)
        studyLog.update(
            request.getTitle(),
            request.getContent(),
            category,
            understanding,
            request.getStudyTime(),
            request.getStudyDate()
        );

        // 7. 저장 및 응답 반환 (DAO 사용)
        StudyLog updatedStudyLog = studyLogDao.update(studyLog);
        return StudyLogResponse.from(updatedStudyLog);
    }

    // ========== DELETE ==========

    /**
     * 학습 일지를 삭제합니다.
     *
     * @param id 삭제할 학습 일지 ID
     * @return 삭제 결과 응답
     * @throws ResourceNotFoundException 해당 ID의 학습 일지가 없는 경우
     * @throws ForbiddenException 다른 사용자의 학습 일지를 삭제하려는 경우
     */
    public StudyLogDeleteResponse deleteStudyLog(Long id) {
        // 1. Get current authenticated user ID
        Long userId = getCurrentUserId();

        // 2. 학습 일지 조회 및 존재 여부 확인 (DAO 사용)
        Optional<StudyLog> studyLogOpt = studyLogDao.findById(id);
        StudyLog studyLog = studyLogOpt.orElseThrow(() ->
            new ResourceNotFoundException("Study Log", id)
        );

        // 3. Verify ownership
        if (!studyLog.getUserId().equals(userId)) {
            log.warn("User {} attempted to delete study log {} owned by user {}", userId, id, studyLog.getUserId());
            throw new ForbiddenException("Study Log", id);
        }

        // 4. 삭제 수행 (DAO 사용)
        studyLogDao.deleteById(id);

        // 5. 삭제 결과 반환
        return StudyLogDeleteResponse.of(id);
    }

    /**
     * 학습 일지 총 개수를 반환합니다.
     *
     * @return 학습 일지 총 개수
     */
    public long getStudyLogCount() {
        return studyLogDao.count();
    }
}